name: Deploy to EC2

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy text file to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "Deploying text file..."
          mkdir -p /home/${{ secrets.EC2_USER }}/deployments
          echo "This is a sample text file" > /home/${{ secrets.EC2_USER }}/deployments/example.txt
          echo "Deployment complete!"
